In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('fake_job_postings.csv',encoding='latin-1')

C:\Users\bpkmo\AppData\Local\Temp\ipykernel_19216\2802033515.py:1: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('fake_job_postings.csv',encoding='latin-1')


In [3]:
data.head()

job_id                                      title            location  \
0      1                           Marketing Intern    US, NY, New York   
1      2  Customer Service - Cloud Video Production      NZ, , Auckland   
2      3    Commissioning Machinery Assistant (CMA)       US, IA, Wever   
3      4          Account Executive - Washington DC  US, DC, Washington   
4      5                        Bill Review Manager  US, FL, Fort Worth   

  department salary_range                                    company_profile  \
0  Marketing          NaN  We're Food52, and we've created a groundbreaki...   
1    Success          NaN  90 Seconds, the worlds Cloud Video Production ...   
2        NaN          NaN  Valor Services provides Workforce Solutions th...   
3      Sales          NaN  Our passion for improving quality of life thro...   
4        NaN          NaN  SpotSource Solutions LLC is a Global Human Cap...   

                                         description  \
0  Food52, a fast-growing, James Beard Award-winn...   
1  Organised - Focused - Vibrant - Awesome!Do you...   
2  Our client, located in Houston, is actively se...   
3  THE COMPANY: ESRI – Environmental Systems Re...   
4  JOB TITLE: Itemization Review ManagerLOCATION:...   

                                        requirements  \
0  Experience with content management systems a m...   
1  What we expect from you:Your key responsibilit...   
2  Implement pre-commissioning and commissioning ...   
3  EDUCATION: Bachelor’s or Master’s in GIS,...   
4  QUALIFICATIONS:RN license in the State of Texa...   

                                            benefits telecommuting  \
0                                                NaN           0.0   
1  What you will get from usThrough being part of...           0.0   
2                                                NaN           0.0   
3  Our culture is anything but corporate—we hav...           0.0   
4                              Full Benefits Offered           0.0   

  has_company_logo has_questions employment_type required_experience  \
0              1.0           0.0           Other          Internship   
1              1.0           0.0       Full-time      Not Applicable   
2              1.0           0.0             NaN                 NaN   
3              1.0           0.0       Full-time    Mid-Senior level   
4              1.0           1.0       Full-time    Mid-Senior level   

  required_education                   industry              function  \
0                NaN                        NaN             Marketing   
1                NaN  Marketing and Advertising      Customer Service   
2                NaN                        NaN                   NaN   
3  Bachelor's Degree          Computer Software                 Sales   
4  Bachelor's Degree     Hospital & Health Care  Health Care Provider   

   fraudulent  
0         0.0  
1         0.0  
2         0.0  
3         0.0  
4         0.0

In [4]:
data.columns

Index(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'description', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent'],
      dtype='object')

In [5]:
data.dtypes

job_id                  object
title                   object
location                object
department              object
salary_range            object
company_profile         object
description             object
requirements            object
benefits                object
telecommuting           object
has_company_logo        object
has_questions           object
employment_type         object
required_experience     object
required_education      object
industry                object
function                object
fraudulent             float64
dtype: object

In [6]:
data.isnull().sum()

job_id                  16249
title                  495103
location               587255
department             622941
salary_range           626488
company_profile        615036
description            615869
requirements           618532
benefits               622978
telecommuting          615881
has_company_logo       615883
has_questions          615883
employment_type        619286
required_experience    622830
required_education     623864
industry               620697
function               622240
fraudulent             615884
dtype: int64

In [7]:
data = data[['description','fraudulent']]

In [8]:
data.head()

description  fraudulent
0  Food52, a fast-growing, James Beard Award-winn...         0.0
1  Organised - Focused - Vibrant - Awesome!Do you...         0.0
2  Our client, located in Houston, is actively se...         0.0
3  THE COMPANY: ESRI – Environmental Systems Re...         0.0
4  JOB TITLE: Itemization Review ManagerLOCATION:...         0.0

In [9]:
data=data.dropna()

In [10]:
data.shape

(17585, 2)

In [11]:
data['fraudulent'].value_counts()

fraudulent
0.0    16736
1.0      849
Name: count, dtype: int64

In [12]:
data.shape

(17585, 2)

In [13]:
data.head()

description  fraudulent
0  Food52, a fast-growing, James Beard Award-winn...         0.0
1  Organised - Focused - Vibrant - Awesome!Do you...         0.0
2  Our client, located in Houston, is actively se...         0.0
3  THE COMPANY: ESRI – Environmental Systems Re...         0.0
4  JOB TITLE: Itemization Review ManagerLOCATION:...         0.0

In [14]:
data['fraudulent'].value_counts()

fraudulent
0.0    16736
1.0      849
Name: count, dtype: int64

In [15]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [16]:
def preprocess_data(data):
    
    # Convert text to lowercase
    data['text'] = data['text'].str.strip().str.lower()
    return data

In [17]:
data.head()

description  fraudulent
0  Food52, a fast-growing, James Beard Award-winn...         0.0
1  Organised - Focused - Vibrant - Awesome!Do you...         0.0
2  Our client, located in Houston, is actively se...         0.0
3  THE COMPANY: ESRI – Environmental Systems Re...         0.0
4  JOB TITLE: Itemization Review ManagerLOCATION:...         0.0

In [18]:
x=data['description']
y=data['fraudulent']

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x,y, stratify=y, test_size=0.25, random_state=42)

In [20]:
# Vectorize text reviews to numbers
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer(stop_words='english')
from sklearn.feature_extraction.text import HashingVectorizer
hvectorizer = HashingVectorizer(n_features=52991,norm=None,alternate_sign=False)
x_train = hvectorizer.fit_transform(x_train).toarray()
x_test = hvectorizer.transform(x_test).toarray()

In [21]:
print(x_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [22]:
from sklearn.metrics import accuracy_score

In [23]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf=rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
acc= accuracy_score(y_test,y_pred)
acc 

0.9788492153741187

In [24]:
import pickle
filename = 'Random_forest1.sav'
pickle.dump(rf, open(filename, 'wb'))

In [25]:
import pickle
filename = 'Random_forest1.sav'
model = pickle.load(open(filename, 'rb'))

In [26]:
abc = [''' Food52, a fast-growing, James Beard Award-winning online food community and crowd-sourced and curated recipe hub, is currently interviewing full- and part-time unpaid interns to work in a small team of editors, executives, and developers in its New York City headquarters.Reproducing and/or repackaging existing Food52 content for a number of partner sites, such as Huffington Post, Yahoo, Buzzfeed, and more in their various content management systemsResearching blogs and websites for the Provisions by Food52 Affiliate ProgramAssisting in day-to-day affiliate program support, such as screening affiliates and assisting in any affiliate inquiriesSupporting with PR &amp; Events when neededHelping with office administrative work, such as filing, mailing, and preparing for meetingsWorking with developers to document bugs and suggest improvements to the siteSupporting the marketing and executive staff''']
result = model.predict(hvectorizer.transform(abc))
result = result[0]
result
if result==0:
    print('The Job post is Genuine')
else:
    print('The Job post is Fake')

The Job post is Genuine


In [27]:
abc = [''' IC&amp;E Technician | Bakersfield, CA Mt. PosoPrincipal Duties and Responsibilities: Calibrates, tests, maintains, troubleshoots, and installs all power plant instrumentation, control systems and electrical equipment.Performs maintenance on motor control centers, motor operated valves, generators, excitation equipment and motors.Performs preventive, predictive and corrective maintenance on equipment, coordinating work with various team members.Designs and installs new equipment and/or system modifications.Troubleshoots and performs maintenance on DC backup power equipment, process controls, programmable logic controls (PLC), and emission monitoring equipment.Uses maintenance reporting system to record time and material use, problem identified and corrected, and further action required; provides complete history of maintenance on equipment.Schedule, coordinate, work with and monitor contractors on specific tasks, as required.Follows safe working practices at all times.Identifies safety hazards and recommends solutions.Follows environmental compliance work practices.Identifies environmental non-compliance problems and assist in implementing solutions.Assists other team members and works with all departments to support generating station in achieving their performance goals.Trains other team members in the areas of instrumentation, control, and electrical systems.Performs housekeeping assignments, as directed.Conduct equipment and system tagging according to company and plant rules and regulations.Perform equipment safety inspections, as required, and record results as appropriate. Participate in small construction projects.  Read and interpret drawings, sketches, prints, and specifications, as required.Orders parts as needed to affect maintenance and repair.Performs Operations tasks on an as-needed basis and other tasks as assigned.Available within a reasonable response time for emergency call-ins and overtime, plus provide acceptable off-hour contact by phone and company pager.          Excellent Verbal and Written Communications Skills:Ability to coordinate work activities with other team members on technical subjects across job families.Ability to work weekends, holidays, and rotating shifts, as required. ''']
result = model.predict(hvectorizer.transform(abc))
result = result[0]
result
if result==0:
    print('The Job post is Genuine')
else:
    print('The Job post is Fake')

The Job post is Fake


In [28]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb = xgb.fit(x_train,y_train)
y_pred = xgb.predict(x_test)
acc = accuracy_score(y_pred,y_test)
acc #0.9816554809843401

0.979304070957471

In [29]:
import pickle
filename = 'XGBoost1.sav'
pickle.dump(xgb, open(filename, 'wb'))

In [30]:
filename = 'XGBoost1.sav'
model1 = pickle.load(open(filename, 'rb'))

In [31]:
abc = [''' IC&amp;E Technician | Bakersfield, CA Mt. PosoPrincipal Duties and Responsibilities: Calibrates, tests, maintains, troubleshoots, and installs all power plant instrumentation, control systems and electrical equipment.Performs maintenance on motor control centers, motor operated valves, generators, excitation equipment and motors.Performs preventive, predictive and corrective maintenance on equipment, coordinating work with various team members.Designs and installs new equipment and/or system modifications.Troubleshoots and performs maintenance on DC backup power equipment, process controls, programmable logic controls (PLC), and emission monitoring equipment.Uses maintenance reporting system to record time and material use, problem identified and corrected, and further action required; provides complete history of maintenance on equipment.Schedule, coordinate, work with and monitor contractors on specific tasks, as required.Follows safe working practices at all times.Identifies safety hazards and recommends solutions.Follows environmental compliance work practices.Identifies environmental non-compliance problems and assist in implementing solutions.Assists other team members and works with all departments to support generating station in achieving their performance goals.Trains other team members in the areas of instrumentation, control, and electrical systems.Performs housekeeping assignments, as directed.Conduct equipment and system tagging according to company and plant rules and regulations.Perform equipment safety inspections, as required, and record results as appropriate. Participate in small construction projects.  Read and interpret drawings, sketches, prints, and specifications, as required.Orders parts as needed to affect maintenance and repair.Performs Operations tasks on an as-needed basis and other tasks as assigned.Available within a reasonable response time for emergency call-ins and overtime, plus provide acceptable off-hour contact by phone and company pager.          Excellent Verbal and Written Communications Skills:Ability to coordinate work activities with other team members on technical subjects across job families.Ability to work weekends, holidays, and rotating shifts, as required. ''']
result = model1.predict(hvectorizer.transform(abc))
result = result[0]
result
if result==0:
    print('The Job post is Genuine')
else:
    print('The Job post is Fake')

The Job post is Fake


In [32]:
abc = [''' Food52, a fast-growing, James Beard Award-winning online food community and crowd-sourced and curated recipe hub, is currently interviewing full- and part-time unpaid interns to work in a small team of editors, executives, and developers in its New York City headquarters.Reproducing and/or repackaging existing Food52 content for a number of partner sites, such as Huffington Post, Yahoo, Buzzfeed, and more in their various content management systemsResearching blogs and websites for the Provisions by Food52 Affiliate ProgramAssisting in day-to-day affiliate program support, such as screening affiliates and assisting in any affiliate inquiriesSupporting with PR &amp; Events when neededHelping with office administrative work, such as filing, mailing, and preparing for meetingsWorking with developers to document bugs and suggest improvements to the siteSupporting the marketing and executive staff''']
result = model1.predict(hvectorizer.transform(abc))
result = result[0]
result
if result==0:
    print('The Job post is Genuine')
else:
    print('The Job post is Fake')

The Job post is Fake


In [33]:
from sklearn.linear_model import LogisticRegression
lr =LogisticRegression()
lr = lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
acc=accuracy_score(y_pred,y_test)
acc #0.9827740492170023

C:\Users\bpkmo\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9783943597907664

In [34]:
import pickle
filename = 'Logistic_regression1.sav'
pickle.dump(lr,open(filename, 'wb'))

In [35]:
filename = 'Logistic_regression1.sav'
model2 = pickle.load(open(filename, 'rb'))

In [36]:
abc = [''' Food52, a fast-growing, James Beard Award-winning online food community and crowd-sourced and curated recipe hub, is currently interviewing full- and part-time unpaid interns to work in a small team of editors, executives, and developers in its New York City headquarters.Reproducing and/or repackaging existing Food52 content for a number of partner sites, such as Huffington Post, Yahoo, Buzzfeed, and more in their various content management systemsResearching blogs and websites for the Provisions by Food52 Affiliate ProgramAssisting in day-to-day affiliate program support, such as screening affiliates and assisting in any affiliate inquiriesSupporting with PR &amp; Events when neededHelping with office administrative work, such as filing, mailing, and preparing for meetingsWorking with developers to document bugs and suggest improvements to the siteSupporting the marketing and executive staff''']
result = model2.predict(hvectorizer.transform(abc))
result = result[0]
result
if result==0:
    print('The Job post is Genuine')
else:
    print('The Job post is Fake')

The Job post is Genuine


In [37]:
abc = [''' IC&amp;E Technician | Bakersfield, CA Mt. PosoPrincipal Duties and Responsibilities: Calibrates, tests, maintains, troubleshoots, and installs all power plant instrumentation, control systems and electrical equipment.Performs maintenance on motor control centers, motor operated valves, generators, excitation equipment and motors.Performs preventive, predictive and corrective maintenance on equipment, coordinating work with various team members.Designs and installs new equipment and/or system modifications.Troubleshoots and performs maintenance on DC backup power equipment, process controls, programmable logic controls (PLC), and emission monitoring equipment.Uses maintenance reporting system to record time and material use, problem identified and corrected, and further action required; provides complete history of maintenance on equipment.Schedule, coordinate, work with and monitor contractors on specific tasks, as required.Follows safe working practices at all times.Identifies safety hazards and recommends solutions.Follows environmental compliance work practices.Identifies environmental non-compliance problems and assist in implementing solutions.Assists other team members and works with all departments to support generating station in achieving their performance goals.Trains other team members in the areas of instrumentation, control, and electrical systems.Performs housekeeping assignments, as directed.Conduct equipment and system tagging according to company and plant rules and regulations.Perform equipment safety inspections, as required, and record results as appropriate. Participate in small construction projects.  Read and interpret drawings, sketches, prints, and specifications, as required.Orders parts as needed to affect maintenance and repair.Performs Operations tasks on an as-needed basis and other tasks as assigned.Available within a reasonable response time for emergency call-ins and overtime, plus provide acceptable off-hour contact by phone and company pager.          Excellent Verbal and Written Communications Skills:Ability to coordinate work activities with other team members on technical subjects across job families.Ability to work weekends, holidays, and rotating shifts, as required. ''']
result = model1.predict(hvectorizer.transform(abc))
result = result[0]
result
if result==0:
    print('The Job post is Genuine')
else:
    print('The Job post is Fake')

The Job post is Fake
